image: docker:latest

services:
  - docker:dind

build:
  stage: build
  only:
    - tags
    - branches
  script:
    - apt-get update && apt-get install -y add git bash
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - bash scripts/ci-build.sh
